### PR TITLE
review

### PR DESCRIPTION
**Pull request by akaljotdhillon**
please check it

### CODE REVIEW

**Comment by ShahJinali** [comment]
I need the installation steps and updated README file for passing the inputs to algorithm

**Comment by akaljotdhillon** [comment]
> I need the installation steps and updated README file for passing the inputs to algorithm

Please refer to site mentioned below to download and install gsl library used:
https://www.gnu.org/software/gsl/

To run (MacOS):
1. Go to folder 
2. make clean
3. make
4. cd bin
5. ./main

**Comment by akaljotdhillon** [comment]
> I need the installation steps and updated README file for passing the inputs to algorithm

Please refer to site mentioned below to download and install gsl library used: [](https://www.gnu.org/software/gsl/)

**Comment by ShahJinali** [comment]
I was trying to run the project and when I use make command it throws the following error.

src/main.c:14:10: fatal error: externs.h: No such file or directory
 #include "externs.h"
          ^~~~~~~~~~~
compilation terminated.
src/data_preprocess.c:2:10: fatal error: externs.h: No such file or directory
 #include "externs.h"
          ^~~~~~~~~~~
compilation terminated.
src/fileio.c:2:10: fatal error: externs.h: No such file or directory
 #include "externs.h"
          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:26: bin/main.exe] Error 1

**Comment by ShahJinali** [comment]
There is "externs.h" file used in src/main.c , src/fileio.c  but there is no such "externs.h" header file inside include folder

**Comment by Ripudaman92** [comment]
sorry about that.
we have just updated everything to master branch including the files that were missing. we have not finished the readme file yet. The code could still be tested using the following steps:
1. install 'mingw' and extract 'msys'.
2. add/set environmental variables.
3. rename migw-makefile.exe to make (file present in C->MinGW->bin)
4. Compile gsl library. (navigate to lib gsl2.6 and use ./configure to compile gsl library)
5. Place nu-sense project to lib folder(C:\MinGW\msys\1.0\home\user\nu-sense)
6. navigate to nu-sense and use "make".
7. run main.exe in bin folder

**Comment by akaljotdhillon** [comment]
At step 1. please extract msys to MinGW folder

**Comment by ShahJinali** [comment]
Problem is not with the installation . Basically ,review is on branch Eigen-Calculation-Step1-3 ; when I try to run the project it shows the error of missing  "extern.h" file.

Should I download the Project from Master branch ?

**Comment by akaljotdhillon** [comment]
Yes please, download whole project from master branch.

**Comment by ShahJinali** [comment]
So, I download the project from master branch. The project was build and run successfully. I understood the steps shown while running the project.But, I couldn't understand the output file i.e. output.csv and sensor_history.csv.

There are certain sensors out of range and according to my understanding the sensors which are out of range should not be considered during fusion algorithm.However, your fusion algorithm is just stating that sensors are out of range but those values are considered while computing the fused value.

**Comment by ShahJinali** [comment]
There are two more reviewer .Please add them as well.

**Comment by Ripudaman92** [comment]
we have already sent requests to add contributors to other members but they have not accepted it so far

**Comment by Ripudaman92** [comment]
> So, I download the project from master branch. The project was build and run successfully. I understood the steps shown while running the project.But, I couldn't understand the output file i.e. output.csv and sensor_history.csv.
> 
> There are certain sensors out of range and according to my understanding the sensors which are out of range should not be considered during fusion algorithm.However, your fusion algorithm is just stating that sensors are out of range but those values are considered while computing the fused value.

from whatever we have understood through the paper, sensor fusion algorithm has a functionality that if some sensors have values that are out of range, those values would be discarded in the last step thats is step 7

**Comment by ShahJinali** [comment]
> There are two more reviewer .Please add them as well.

Can you re-send the collaboration request because they haven't  received it!

**Comment by ShahJinali** [comment]
> > So, I download the project from master branch. The project was build and run successfully. I understood the steps shown while running the project.But, I couldn't understand the output file i.e. output.csv and sensor_history.csv.
> > There are certain sensors out of range and according to my understanding the sensors which are out of range should not be considered during fusion algorithm.However, your fusion algorithm is just stating that sensors are out of range but those values are considered while computing the fused value.
> 
> from whatever we have understood through the paper, sensor fusion algorithm has a functionality that if some sensors have values that are out of range, those values would be discarded in the last step thats is step 7

**Comment by ShahJinali** [comment]
Software is

**Comment by ShahJinali** [comment]
> > > So, I download the project from master branch. The project was build and run successfully. I understood the steps shown while running the project.But, I couldn't understand the output file i.e. output.csv and sensor_history.csv.
> > > There are certain sensors out of range and according to my understanding the sensors which are out of range should not be considered during fusion algorithm.However, your fusion algorithm is just stating that sensors are out of range but those values are considered while computing the fused value.
> > 
> > 
> > from whatever we have understood through the paper, sensor fusion algorithm has a functionality that if some sensors have values that are out of range, those values would be discarded in the last step thats is step 7

This is what I understood when I had conversation with professor about the same topic. You can still confirm it!

**Comment by ShahJinali** [comment]
Everything else is looking good. So, you can merge the pull request!

**Comment by rushabh1410** [comment]
> > There are two more reviewer .Please add them as well.
> 
> Can you re-send the collaboration request because they haven't received it!

Yes,Please i didn't receive the request.

**Comment by ShahJinali** [comment]
Hello,

Can you close this pull request and open the new pull request with latest code.

**Pull request closed without merging**
